### ISSUE TITLE
docker image fails to build: EnvironmentError: mysql_config not found

### ISSUE THREAD

**Issue by swaroopgj** [mvdoc/psiturk-docker#1]
Removing intermediate container f8eac58de134
Step 6 : RUN pip install --upgrade setuptools requests mysql-python psiturk
 ---> Running in 47abe3ff38e5
Collecting setuptools
  Downloading setuptools-27.3.1-py2.py3-none-any.whl (467kB)
Collecting requests
  Downloading requests-2.11.1-py2.py3-none-any.whl (514kB)
Collecting mysql-python
  Downloading MySQL-python-1.2.5.zip (108kB)
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vALZzI/mysql-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vALZzI/mysql-python/
ERROR: Service 'psiturk' failed to build: The command '/bin/sh -c pip install --upgrade setuptools requests mysql-python psiturk' returned a non-zero code: 1

**Comment by mvdoc** [comment]
Closed by #2
